version: '3.8'
services:
  mysql_db:
    image: mariadb
    restart: always
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:   # Set up mysql database name and password
      MYSQL_DATABASE: DEV_S1
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    
    networks:
      - app-tier
    ports:
      - "33061:3306"
    volumes:
        - ./data/init.sql:/docker-entrypoint-initdb.d/1.sql    

  postman:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    networks:
     - app-tier


volumes: 
  data:


networks:
  app-tier:
    driver: bridge